---
title: "CAanalysis"
author: "julesolson"
date: "2021-02-19"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Analysis of EVTs in California which are not owned by TNC

## The Data

**215** EVTs exist in CA, of which **171** are represented in TNC's ownership

```{r echo=FALSE, results='asis', warning=FALSE}
evt_ca <- read.csv("./data/US200EVT_CA.csv")
tnc_ca <- read.csv("./data/US200EVT_CA_TNC.csv")
library(knitr)

kable(evt_ca[1:5, ], caption="EVT data for all of California (first five lines)")
kable(tnc_ca[1:5, ], caption="EVT data for EVTs owned by The Nature Conservancy (first five lines)")
```


##Most Prevalent Unrepresented EVTs

Identifying the EVTs not represented in TNC's ownership which make up the largest proportion of CA

```{r echo=FALSE, warning=FALSE, include=FALSE}
#Processing data for the Top 10 graph
library(tidyverse)
library(ggplot2)

#Rename count columns and add percent and rank columns
evt_ca<-evt_ca%>%
  rename(COUNT_CA=COUNT)%>%
  arrange(desc(COUNT_CA))%>%
  mutate(PERCENT_CA=round(COUNT_CA/sum(COUNT_CA)*100,4),
         RANK_CA=1:pull(tally(evt_ca)))
tnc_ca<-tnc_ca%>%
  rename(COUNT_TNC=COUNT)%>%
  arrange(desc(COUNT_TNC))%>%
  mutate(PERCENT_TNC=round(COUNT_TNC/sum(COUNT_TNC)*100,4),
         RANK_TNC=1:pull(tally(tnc_ca)))

#join the two data frames
ca <- left_join(evt_ca, tnc_ca) %>%
  replace(is.na(.), 0)

#Filter this data so that we only have the EVTs in CA not owned by TNC
ca_notowned<-ca%>%
  filter(COUNT_TNC==0)%>%
  select(-COUNT_TNC,-PERCENT_TNC,-RANK_TNC)

#Grab the 10 largest EVTs not owned
ca_tennotowned<-slice(ca_notowned,1:10)

#Order the top 10 so that they are arranged by size in our plot rather than alphabetically
orderca_tennotowned<-ca_tennotowned%>%
  arrange(desc(PERCENT_CA))%>%
  mutate(EVT_NAME = factor(EVT_NAME, levels=EVT_NAME))

#Get rid of space in "Sparsely Vegetated" so we can assign colors manually
library(stringr)
EVT_PHYSNS<-str_replace(orderca_tennotowned$EVT_PHYS," ","")
orderca_tennotowned$EVT_PHYSNS<-EVT_PHYSNS
orderca_tennotowned=subset(orderca_tennotowned, select=-EVT_PHYS)
```
```{r echo=FALSE, warning=FALSE, fig.width=9}
ggplot(orderca_tennotowned, aes(x=EVT_NAME, y=PERCENT_CA, fill=EVT_PHYSNS))+
  geom_bar(stat='identity',position='dodge')+
  coord_flip()+
  labs(x="EVT",y="Percent of CA",title="Top 10 EVT's in CA not owned by TNC")+
  scale_fill_manual(values=c(Conifer="olivedrab4", Riparian="navy", Grassland="navajowhite1", Shrubland="orange2", Hardwood= "orange4", SparselyVegetated="olivedrab1"))
```

##Unrepresented EVT PHYS Types

```{r echo=FALSE, warning=FALSE, include=FALSE}
#Now group all unowned EVTs by EVT_PHYS
phys_ca_notowned<-ca_notowned %>% group_by(EVT_PHYS)%>%
  summarise(PHYS_PERCENT_CA = sum(PERCENT_CA))%>%
  arrange(desc(PHYS_PERCENT_CA))
```

```{r echo=FALSE, warning= FALSE, fig.width=9}
ggplot(phys_ca_notowned, aes(x=EVT_PHYS,y=PHYS_PERCENT_CA))+
  geom_bar(stat='identity', position='dodge')+
  xlab("EVT Phys Type")+
  ylab("Percent of CA Area")+
  ggtitle("Percent Areas of EVT PHYS Types in CA not owned by TNC")+
  theme_bw()
```

