---
title: "CONUSanalysis"
author: "julesolson"
date: "2021-02-21"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Analysis of EVTs in the contuguous United States which are not owned by TNC

## The Data

**856** EVTs exist in CONUS, of which **764** are represented in TNC's ownership

```{r echo=FALSE, warning=FALSE}
evt_conus <- read.csv("./data/US200EVT_CONUS.csv")
tnc_conus <- read.csv("./data/US200EVT_CONUS_TNC.csv")
library(knitr)

kable(evt_conus[1:5, ], caption="EVT data for all of the contiguous United States (first five lines)")
kable(tnc_conus[1:5, ], caption="EVT data for EVTs owned by The Nature Conservancy (first five lines)")
```

##Most Prevalent Unrepresented EVTs

Identifying the EVTs not represented in TNC's ownership which make up the largest proportion of the contiguous United States

```{r echo=FALSE, warning=FALSE, include=FALSE}
#Processing data for the Top 10 graph
library(tidyverse)
library(ggplot2)

#Rename count columns and add percent and rank columns
evt_conus<-evt_conus%>%
  rename(COUNT_CONUS=COUNT)%>%
  arrange(desc(COUNT_CONUS))%>%
  mutate(PERCENT_CONUS=round(COUNT_CONUS/sum(COUNT_CONUS)*100,4),
         RANK_CONUS=1:pull(tally(evt_conus)))
tnc_conus<-tnc_conus%>%
  rename(COUNT_TNC=COUNT)%>%
  arrange(desc(COUNT_TNC))%>%
  mutate(PERCENT_TNC=round(COUNT_TNC/sum(COUNT_TNC)*100,4),
         RANK_TNC=1:pull(tally(tnc_conus)))

#join the two data frames
conus <- left_join(evt_conus, tnc_conus) %>%
  replace(is.na(.), 0)

#Filter this data so that we only have the EVTs in CA not owned by TNC
conus_notowned<-conus%>%
  filter(COUNT_TNC==0)%>%
  select(-COUNT_TNC,-PERCENT_TNC,-RANK_TNC)

#Grab the 10 largest EVTs not owned
conus_tennotowned<-slice(conus_notowned,1:10)

#Order the top 10 so that they are arranged by size in our plot rather than alphabetically
orderconus_tennotowned<-conus_tennotowned%>%
  arrange(desc(PERCENT_CONUS))%>%
  mutate(EVT_NAME = factor(EVT_NAME, levels=EVT_NAME))

#Get rid of space in "Sparsely Vegetated" so we can assign colors manually
library(stringr)
EVT_PHYSNS<-str_replace(orderconus_tennotowned$EVT_PHYS," ","")
orderconus_tennotowned$EVT_PHYSNS<-EVT_PHYSNS
orderconus_tennotowned=subset(orderconus_tennotowned, select=-EVT_PHYS)
```
```{r echo=FALSE, warning=FALSE, fig.width=9}
ggplot(orderconus_tennotowned, aes(x=EVT_NAME, y=PERCENT_CONUS, fill=EVT_PHYSNS))+
  geom_bar(stat='identity',position='dodge')+
  coord_flip()+
  labs(x="EVT",y="Percent of CONUS",title="Top 10 EVT's in CONUS not owned by TNC")+
  scale_fill_manual(values=c(Conifer="olivedrab4", Riparian="navy", Grassland="navajowhite1", Shrubland="orange2", Hardwood= "orange4", SparselyVegetated="olivedrab1"))
```

##Unrepresented EVT PHYS Types

```{r echo=FALSE, warning=FALSE, include=FALSE}
#Now group all unowned EVTs by EVT_PHYS
phys_conus_notowned<-conus_notowned %>% group_by(EVT_PHYS)%>%
  summarise(PHYS_PERCENT_CONUS = sum(PERCENT_CONUS))%>%
  arrange(desc(PHYS_PERCENT_CONUS))

#Remove unwanted PHYS types
phys_conus_notowned<-phys_conus_notowned%>%
  filter(EVT_PHYS!='Agricultural' & EVT_PHYS!='Developed' & EVT_PHYS!='Snow-Ice' & EVT_PHYS!='Exotic Herbaceous' & EVT_PHYS!= 'Exotic Tree-Shrub')
```

```{r echo=FALSE, warning= FALSE, fig.width=9}
ggplot(phys_conus_notowned, aes(x=EVT_PHYS,y=PHYS_PERCENT_CONUS))+
  geom_bar(stat='identity', position='dodge')+
  xlab("EVT Phys Type")+
  ylab("Percent of CONUS Area")+
  ggtitle("Percent Areas of EVT PHYS Types in CONUS not owned by TNC")+
  theme_bw()
```

