---
title: "MALanalysis"
author: "julesolson"
date: "2021-02-21"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Analysis of EVTs in MAL which are not owned by TNC

## The Data

**236** EVTs exist in MAL, of which **166** are represented in TNC's ownership

```{r echo=FALSE, results='asis', warning=FALSE}
evt_mal <- read.csv("./data/US200EVT_MAL.csv")
tnc_mal <- read.csv("./data/US200EVT_MAL_TNC.csv")
library(knitr)

kable(evt_mal[1:5, ], caption="EVT data for all of MAL (first five lines)")
kable(tnc_mal[1:5, ], caption="EVT data for EVTs owned by The Nature Conservancy (first five lines)")
```


##Most Prevalent Unrepresented EVTs

Identifying the EVTs not represented in TNC's ownership which make up the largest proportion of MAL

```{r echo=FALSE, warning=FALSE, include=FALSE}
#Processing data for the Top 10 graph
library(tidyverse)
library(ggplot2)

#Rename count columns and add percent and rank columns
evt_mal<-evt_mal%>%
  rename(COUNT_MAL=COUNT)%>%
  arrange(desc(COUNT_MAL))%>%
  mutate(PERCENT_MAL=round(COUNT_MAL/sum(COUNT_MAL)*100,4),
         RANK_MAL=1:pull(tally(evt_mal)))
tnc_mal<-tnc_mal%>%
  rename(COUNT_TNC=COUNT)%>%
  arrange(desc(COUNT_TNC))%>%
  mutate(PERCENT_TNC=round(COUNT_TNC/sum(COUNT_TNC)*100,4),
         RANK_TNC=1:pull(tally(tnc_mal)))

#join the two data frames
mal <- left_join(evt_mal, tnc_mal) %>%
  replace(is.na(.), 0)

#Filter this data so that we only have the EVTs in CA not owned by TNC
mal_notowned<-mal%>%
  filter(COUNT_TNC==0 & EVT_PHYS!='Agricultural' & EVT_PHYS!='Developed' & EVT_PHYS!='Snow-Ice' & EVT_PHYS!='Exotic Herbaceous' & EVT_PHYS!= 'Exotic Tree-Shrub')%>%
  select(-COUNT_TNC,-PERCENT_TNC,-RANK_TNC)

#Grab the 10 largest EVTs not owned
mal_tennotowned<-slice(mal_notowned,1:10)

#Order the top 10 so that they are arranged by size in our plot rather than alphabetically
ordermal_tennotowned<-mal_tennotowned%>%
  arrange(desc(PERCENT_MAL))%>%
  mutate(EVT_NAME = factor(EVT_NAME, levels=EVT_NAME))

#Get rid of space in "Sparsely Vegetated" so we can assign colors manually
library(stringr)
EVT_PHYSNS<-str_replace(ordermal_tennotowned$EVT_PHYS," ","")
ordermal_tennotowned$EVT_PHYSNS<-EVT_PHYSNS
ordermal_tennotowned=subset(ordermal_tennotowned, select=-EVT_PHYS)
```
```{r echo=FALSE, warning=FALSE, fig.width=9}
ggplot(ordermal_tennotowned, aes(x=EVT_NAME, y=PERCENT_MAL, fill=EVT_PHYSNS))+
  geom_bar(stat='identity',position='dodge')+
  coord_flip()+
  labs(x="EVT",y="Percent of MAL",title="Top 10 EVT's in MAL not owned by TNC")+
  scale_fill_manual(values=c(Conifer="olivedrab4", Riparian="navy", Grassland="navajowhite1", Shrubland="orange2", Hardwood= "orange4", SparselyVegetated="olivedrab1"))
```

##Unrepresented EVT PHYS Types

```{r echo=FALSE, warning=FALSE, include=FALSE}
#Now group all unowned EVTs by EVT_PHYS
phys_mal_notowned<-mal_notowned %>% group_by(EVT_PHYS)%>%
  summarise(PHYS_PERCENT_MAL = sum(PERCENT_MAL))%>%
  arrange(desc(PHYS_PERCENT_MAL))

#Remove unwanted PHYS types
phys_mal_notowned<-phys_mal_notowned%>%
  filter(EVT_PHYS!='Agricultural' & EVT_PHYS!='Developed' & EVT_PHYS!='Snow-Ice' & EVT_PHYS!='Exotic Herbaceous' & EVT_PHYS!= 'Exotic Tree-Shrub')
```

```{r echo=FALSE, warning= FALSE, fig.width=9}
ggplot(phys_mal_notowned, aes(x=EVT_PHYS,y=PHYS_PERCENT_MAL))+
  geom_bar(stat='identity', position='dodge')+
  xlab("EVT Phys Type")+
  ylab("Percent of MAL Area")+
  ggtitle("Percent Areas of EVT PHYS Types in MAL not owned by TNC")+
  theme_bw()
```

